# Generated by Django 3.2.7 on 2021-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_commentmodel_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionmodel',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
