# Generated by Django 3.2.7 on 2021-10-29 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_suggestionmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
