# Generated by Django 3.2.9 on 2021-12-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_communitymodel_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=240)),
                ('profile_picture', models.ImageField(max_length=144, null=True, upload_to='uploads/profiles/')),
                ('followed_communities', models.TextField(null=True)),
            ],
        ),
    ]
