# Generated by Django 3.2.9 on 2021-12-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_usermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(default='../static/images/default.png', max_length=144, null=True, upload_to='uploads/profiles/{{ username }}/'),
        ),
    ]
