# Generated by Django 3.2.9 on 2021-12-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_usermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='followed_communities',
            field=models.TextField(default='[]'),
        ),
    ]
