# Generated by Django 3.2.9 on 2021-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_usermodel_followed_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.CharField(default="I don't care enough to enter an about section", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(default='../static/images/default.png', max_length=144, null=True, upload_to='uploads/profiles/'),
        ),
    ]
