# Generated by Django 3.2.9 on 2021-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211202_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='friends_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pending_friends_list',
            field=models.TextField(default='[]'),
        ),
    ]
