# Generated by Django 3.2.9 on 2021-12-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_usermodel_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
