# Generated by Django 3.2.9 on 2021-12-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20211207_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='pending_mod_invites',
            field=models.TextField(default='['),
        ),
    ]
