# Generated by Django 3.2.9 on 2021-12-09 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20211209_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
